### ISSUE TITLE
WAN doesn't transmit\receive at 1000mbps

### ISSUE THREAD

**Issue by terente0081** [Chadster766/McWRT#16] opened 2014-09-02 14:46 UTC
Working solution by Chadster766:

Login to the router via SSH using either Linux SSH or Putty with username root and your router's password. 

Enter the below commands:

ifconfig eth1 txqueuelen 1000
ifconfig eth0 txqueuelen 1000

**Comment by mmilburn** [comment] 2015-01-09 16:59
This appears to be caused by the mvneta driver.  Apparently it is fixed in 3.18.x kernels.  Hopefully, the fixes will be backported to 3.14.x.  If not, it probably wouldn't be too bad to roll a mvebu specific backport for CC.

**Closed** 2015-08-17 06:18 UTC
